<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>My Github website</title>
</head>
<body>
  <h1>My Github website</h1>

  <img src="Me.jpeg"  width="170" />

  <h3>Interests</h3>
  <ul>
    <li>I like playing Video Games</li>
    <li>I also like to go fishing</li>
  </ul>

  <h3>Cool sites</h3>
  <ol>
    <li><a href="chess.com">GitHub</a></li>
    <li><a href="neal.fun">Homework portal</a></li>
  </ol>

  <h3>About</h3>
  <p>
    Hello my name is Gaven Stecher I am a sophmore at BSU I am a computer science major.
  </p>
</body>
</html>
